import JobCard from "@/Component/Card";
import Head from "next/head";
import { Grid } from "@mui/material";
import { parseCookies } from "nookies";
import cookie from "js-cookie";
import { useState, useEffect } from "react";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import Modal from "@mui/material/Modal";
import ReactHtmlParser from "react-html-parser";

const style = {
  position: "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -25%)",
  width: 700,
  bgcolor: "background.paper",
  border: "1px solid #000",
  boxShadow: 24,
  p: 4,
};

const Home = () => {
  const cookies = parseCookies();
  const token = cookies?.access;
  const [jobPost, setJobPost] = useState([]);
  const [singleJob, setSingleJob] = useState([]);

  console.log("jobPost", jobPost);

  const getJobData = async () => {
    var myHeaders = new Headers();
    myHeaders.append("Authorization", `Bearer ${token}`);

    var requestOptions = {
      method: "GET",
      headers: myHeaders,
      redirect: "follow",
    };

    const job = await fetch(
      `https://nomanhasan.pythonanywhere.com/api/view/`,
      requestOptions
    );

    const jobData = await job.json();
    setJobPost(jobData.data);
  };

  useEffect(() => {
    getJobData();
  }, []);

  const [open, setOpen] = useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);

  const giveMeID = (id) => {
    handleOpen();

    setSingleJob(
      jobPost.filter((post) => {
        return post.id == id;
      })
    );
  };

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        sx={{ marginTop: 8, position: "absolute" }}
        container
        direction="column"
        justifyContent="center"
        alignItems="center"
      >
        {jobPost?.map((post) => (
          <JobCard giveMeID={giveMeID} key={post.id} post={post} />
        ))}
      </Grid>
      <Modal
        // sx={{ overflowY: "auto" }}
        open={open}
        onClose={handleClose}
        aria-labelledby="modal-modal-title"
        aria-describedby="modal-modal-description"
      >
        <Box
          sx={{
            bgcolor: "white",
            margin: 3,
            p: 4,
            boxShadow: 24,
            height: 500,
            overflowY: "auto",
          }}
        >
          <Typography id="modal-modal-title" variant="h6" component="h2">
            {singleJob[0]?.title}
          </Typography>
          <span>{singleJob[0]?.company_name}</span>
          <Typography id="modal-modal-description" sx={{ mt: 2 }}>
            <Typography id="modal-modal-title" variant="h6" component="h6">
              Overview
            </Typography>
            {singleJob[0]?.overview}
          </Typography>
          <Typography id="modal-modal-description" sx={{ mt: 2 }}>
            <Typography id="modal-modal-title" variant="h6" component="h6">
              Responsibilities
            </Typography>
            {ReactHtmlParser(singleJob[0]?.responsibilities)}
          </Typography>
          <Typography id="modal-modal-description" sx={{ mt: 2 }}>
            <Typography id="modal-modal-title" variant="h6" component="h6">
              Requirements
            </Typography>

            {ReactHtmlParser(singleJob[0]?.requirements)}
          </Typography>
          <Typography id="modal-modal-title" variant="h6" component="h6">
            Type : {singleJob[0]?.job_type}
          </Typography>
          <Typography id="modal-modal-title" variant="h6" component="h6">
            Location : {singleJob[0]?.location}
          </Typography>
          <Typography id="modal-modal-title" variant="h6" component="h6">
            Shift : {singleJob[0]?.shift}
          </Typography>
        </Box>
      </Modal>
    </div>
  );
};

export default Home;
